---
title: "PM591 - Final Project"
author: "Brandyn Ruiz"
date: "4/6/2021"
output: pdf_document
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(rpart)
library(rattle)
library(mlr)
library(glmnet)
library(pROC)
library(ggplot2)
library(randomForest)
library(tidyverse)
```


```{r}
NIS <- read.csv('NIS2012-200K.csv')

NIS <- NIS%>%
  select(AGE, AGE_NEONATE, AWEEKEND, AMONTH, APRDRG, APRDRG_Risk_Mortality, APRDRG_Severity,
         CM_AIDS, CM_ALCOHOL, CM_ANEMDEF, CM_ARTH, CM_BLDLOSS, CM_CHF, CM_CHRNLUNG, CM_COAG,
         CM_DEPRESS, CM_DM, CM_DMCX, CM_DRUG, CM_HTN_C, CM_HYPOTHY, CM_LIVER,
         CM_LYMPH, CM_LYTES, CM_METS, CM_NEURO, CM_OBESE, CM_PARA, CM_PERIVASC,
         CM_PSYCH, CM_PULMCIRC, CM_RENLFAIL, CM_TUMOR, CM_ULCER, CM_VALVE,
         CM_WGHTLOSS, DIED, DISPUNIFORM, DQTR, DRG, DRG_NoPOA, DRG24, DX1:DX25,
         DXCCS1:DXCCS25, ELECTIVE, FEMALE, HOSP_DIVISION, HOSPBRTH, KEY_NIS, LOS,
         NCHRONIC, NDX, NEOMAT, NIS_STRATUM, NPR, ORPROC, PAY1, PL_NCHS2006,
         PR1:PR15, PRCCS1:PRCCS15, PRDAY1, PRDAY2:PRDAY15, RACE, TRAN_IN, TRAN_OUT,
         YEAR, ZIPINC_QRTL)

NIS$PL_NCHS2006 <- factor(NIS$PL_NCHS2006)
NIS$AGE_NEONATE <- factor(NIS$AGE_NEONATE, levels = c(0,1), labels = c('Non-neonatal age', 'Neontal Age'))
NIS$APRDRG_Risk_Mortality <- factor(NIS$APRDRG_Risk_Mortality, levels = c(0,1,2,3,4), labels = c('Not Specified', 'Minor Likelihood', 'Moderate Likelihood', 'Major Likelihood', 'Extreme Likelihood'))
NIS$APRDRG_Severity <- factor(NIS$APRDRG_Severity, levels = c(0,1,2,3,4), labels = c('Not Specified', 'Minor Loss', 'Moderate Loss', 'Major Loss', 'Extreme Loss'))
NIS$DIED <- factor(NIS$DIED, levels = c(0,1), labels = c('Not Dead', 'Died'))
NIS$DISPUNIFORM <- factor(NIS$DISPUNIFORM)
NIS$DQTR <- factor(NIS$DQTR)
NIS$ELECTIVE <- factor(NIS$ELECTIVE, levels = c(1,0), labels = c('Elective', 'Non-elective'))
NIS$FEMALE <- factor(NIS$FEMALE, levels = c(0,1), labels = c('Male', 'Female'))
NIS$HOSP_DIVISION <- factor(NIS$HOSP_DIVISION, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9), labels = c('New England', 'Middle Atlantic', 'East North Central', 'West North Central', 'South Atlantic', 'East South Central', 'West South Central', 'Mountain', 'Pacific'))
NIS$HOSPBRTH <- factor(NIS$HOSPBRTH, levels = c(0, 1), labels = c('Not hospital birth', 'Hospital Birth'))
NIS$NEOMAT <- factor(NIS$NEOMAT)
NIS$ORPROC <- factor(NIS$ORPROC, levels = c(0, 1), labels = c('No Major Operation', 'Major Operation'))
NIS$PAY1 <- factor(NIS$PAY1, levels = c(1, 2, 3, 4, 5, 6), labels = c('Medicare', 'Medicaid', 'Private', 'Self-pay', 'No charge', 'Other'))
NIS$RACE <- factor(NIS$RACE, levels = c(1, 2, 3, 4, 5, 6), labels = c('White', 'Black', 'Hispanic', 'Asian', 'Native American', 'Other'))
NIS$TRAN_IN <- factor(NIS$TRAN_IN, levels = c(0,1,2), labels = c('No Transfer', 'Transferred in Hospital', 'Transferred in Facility'))
NIS$TRAN_OUT <- factor(NIS$TRAN_OUT, levels = c(0,1,2), labels = c('No Transfer', 'Transfer out Hospital', 'Transfer out Facility'))
NIS$AWEEKEND <- factor(NIS$AWEEKEND, levels = c(0, 1), labels = c('Weekdays', 'Weekend'))
NIS$AMONTH <- factor(NIS$AMONTH, levels = c(1:12), labels = c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))
```

```{r}
NIS_sample <- NIS%>%
  select(AGE, AWEEKEND, AMONTH, APRDRG, APRDRG_Risk_Mortality, APRDRG_Severity,
         ELECTIVE, FEMALE, LOS, ORPROC, PAY1, RACE, TRAN_OUT, TRAN_IN, ZIPINC_QRTL, DIED)
#AGE_NEONATE

NIS_sample$AGE <- as.numeric(NIS_sample$AGE)
NIS_sample$LOS <- as.numeric(NIS_sample$LOS)

```

```{r Summary Statistics}
table(Occurence = NIS_sample$DIED, Gender = NIS_sample$FEMALE, useNA = 'ifany')

table(Occurence = NIS_sample$DIED, Elected = NIS_sample$ELECTIVE, useNA = 'ifany')

# ggplot(data = NIS_sample, aes(x = AGE))+
#   geom_histogram()+
#   facet_wrap(~DIED, nrow = 2)

NIS_sample <- NIS_sample[complete.cases(NIS_sample),]

ggplot(data = NIS_sample, aes(x = DIED, y = AGE, fill = DIED))+
  geom_boxplot()+
  labs(title = 'Age and Outcome', x = 'Outcome', y = 'Age', fill = 'Outcome')+
  theme_bw()

ggplot(data = NIS_sample%>% filter(DIED == 'Died'), aes(x = AGE, fill = DIED))+
  geom_histogram(bins = 45)+
  labs(title = 'Death Frequencies by Age', x = 'Age', y = 'Frequency', fill = 'Outcome')+
  theme_bw()

table(NIS_sample$DIED)
```


Would have to make summary statistics for the NIS_simple. Includes variables relevant to admission of patient...





## Elementary Logisitc Regression (REFERENCE)

```{r}
sm_size <- floor(0.70*nrow(NIS_sample))

set.seed(2019)
train_ind <- sample(seq_len(nrow(NIS_sample)), size = sm_size)

train <- NIS_sample[train_ind, ]
test <- NIS_sample[-train_ind, ]
```

```{r}
NIS_glm <- glm(DIED ~ ., family = 'binomial', data = train)
summary(NIS_glm)
```

```{r}
DescTools::Conf(NIS_glm)
```

```{r Train Performance}
pred_NIS_train <- factor(predict(NIS_glm, newdata = train, type = 'response') > 0.5)

levels(pred_NIS_train) <- c('Not Dead', 'Dead')
confMatrix_train <- table(true = train$DIED, predicted = pred_NIS_train)

confMatrix_train

error_train <- (confMatrix_train[1,2] + confMatrix_train[2,1])/nrow(train)
round(error_train, 4)
```

```{r}
NIS_glm2 <- glm(DIED ~ ., family = 'binomial', data = test)
DescTools::Conf(NIS_glm2)
```

```{r}
pred_NIS_test <- factor(predict(NIS_glm, newdata = test, type = 'response')> 0.5) #

levels(pred_NIS_test) <- c('Not Dead', 'Dead')

confMatrix_test <- table(true = test$DIED, predicted = pred_NIS_test)

confMatrix_test

error_test <- (confMatrix_test[1,2] + confMatrix_test[2,1])/nrow(test)
print(paste0('Misclassification Error = ', round(error_test, 4)))

sensitivity <- round(confMatrix_test[2,2] / (confMatrix_test[2,1] + confMatrix_test[2,2]), 4)

specificity <- round(confMatrix_test[1,1] / (confMatrix_test[1,1] + confMatrix_test[1,2]), 4)
print(paste0('Sensitivity = ', sensitivity))
print(paste0('Specificity = ', specificity))
```

```{r}
predicted_prob_glm <- predict(NIS_glm, newdata = test)

roc_glm <- roc(test$DIED, predicted_prob_glm, ci = TRUE, of = 'auc')

auc(roc_glm)
ci(roc_glm)

plot(roc_glm, lwd = 4)
```

######## Cutoff point test ########
```{r}
test <- coords(roc_glm, input = 'threshold', best.method = 'youden')

# ROC Curve ggplot form
tibble(
  Cutoff = test$threshold,
  SENS = test$sensitivity,
  SPEC = test$specificity
) %>%
  pivot_longer(., cols = c("SENS", "SPEC"), values_to = "value", names_to = "metric") %>%
  ggplot(aes(x = Cutoff, y = value, color = metric)) +
  geom_point() + 
  geom_line()

# Tabular form
tibble(
  Cutoff = test$threshold,
  SENS = test$sensitivity,
  SPEC = test$specificity,
  SUM = SENS + SPEC
)%>%
  arrange(-SUM, -SENS, -SPEC)%>%
  head(10)



roc_empirical <- 
  ROCit::rocit(score = NIS_glm2$fitted.values, class = NIS_glm2$y)
plot(roc_empirical, YIndex = F)
summary(roc_empirical)
#ciAUC(roc_empirical)
```
######## ######## ######## ########



### Fixing Logistic Regression Model

```{r}
NIS_glm_fix <- glm(DIED ~ . -AWEEKEND - TRAN_OUT - ZIPINC_QRTL, family = 'binomial',
               data = train)
summary(NIS_glm_fix)
```

```{r}
DescTools::Conf(NIS_glm_fix)
```

```{r Fixed Train Performance}
pred_NIS_fix_train <- factor(predict(NIS_glm_fix, newdata = train, type = 'response') > 0.5)

levels(pred_NIS_fix_train) <- c('Not Dead', 'Dead')
confMatrix_train <- table(true = train$DIED, predicted = pred_NIS_fix_train)

confMatrix_train

error_train <- (confMatrix_train[1,2] + confMatrix_train[2,1])/nrow(train)
round(error_train, 4)
```

```{r}
pred_NIS_fix_test <- factor(predict(NIS_glm_fix, newdata = test, type = 'response')> 0.5) #

levels(pred_NIS_fix_test) <- c('Not Dead', 'Dead')

confMatrix_test <- table(true = test$DIED, predicted = pred_NIS_fix_test)

confMatrix_test

error_test <- (confMatrix_test[1,2] + confMatrix_test[2,1])/nrow(test)
print(paste0('Misclassification Error = ', round(error_test, 4)))

sensitivity <- round(confMatrix_test[2,2] / (confMatrix_test[2,1] + confMatrix_test[2,2]), 4)

specificity <- round(confMatrix_test[1,1] / (confMatrix_test[1,1] + confMatrix_test[1,2]), 4)
print(paste0('Sensitivity = ', sensitivity))
print(paste0('Specificity = ', specificity))
```

```{r}
predicted_prob_glm_fix <- predict(NIS_glm_fix, newdata = test)

roc_glm <- roc(test$DIED, predicted_prob_glm_fix, ci = TRUE, of = 'auc')

auc(roc_glm)
ci(roc_glm)

plot(roc_glm, lwd = 4)
```

### LASSO Regression

```{r}
# NIS_sample = NIS_sample[complete.cases(NIS_sample), ]
# # 13910 observations with missing values
# 
# death_tsk = makeClassifTask(id = "Death Occurence", 
#                                  data = NIS_sample, target = "DIED")
# 
# holdout_desc = makeResampleDesc(method='Holdout', stratify = TRUE)
# 
# hold = makeResampleInstance(holdout_desc, task = death_tsk, split=0.7)
# 
# train = hold$train.inds[[1]]
# test = hold$test.inds[[1]]
# 
# lasso_lnr =  makeLearner("classif.cvglmnet", 
#                               fix.factors.prediction = TRUE,
#                               predict.type = "prob",
#                               alpha=1, type.measure='auc')
# This is logistic regression with the lasso penalty (alpha=1)
```

```{r}
# death_lasso = train(learner = lasso_lnr, task = death_tsk, subset=train)
# 
# auc_lasso = max(death_lasso$learner.model$cvm)
# 
# print(auc_lasso)
# 
# lambda.min = death_lasso$learner.model$lambda.min
# extracts the optimal lambda
```

```{r}
# lasso_lambda.min_lnr = makeLearner("classif.glmnet", lambda=lambda.min,
#                               fix.factors.prediction = TRUE,
#                               predict.type = "prob",
#                               alpha=1)
# Creates a new learner where lambda is fixed at the optimal value

# death_lasso_final = train(learner = lasso_lambda.min_lnr, task = death_tsk)
#Takes a really long time
# trains the lasso model with the optimal lambda on entire data set (test + train)
```

### New Data NIS_simple with variables relevant to admission

```{r}
NIS_simple <- NIS%>%
  select(c(1, 3:37, 93:98, 104:105, 152:153, 156))

NIS_simple$AGE <- as.numeric(NIS_simple$AGE)
NIS_simple$LOS <- as.numeric(NIS_simple$LOS)

NIS_simple$CM_AIDS <- factor(NIS_simple$CM_AIDS, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_ALCOHOL <- factor(NIS_simple$CM_ALCOHOL, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_ANEMDEF <- factor(NIS_simple$CM_ANEMDEF, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_ARTH <- factor(NIS_simple$CM_ARTH, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_BLDLOSS <- factor(NIS_simple$CM_BLDLOSS, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_CHF <- factor(NIS_simple$CM_CHF, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_CHRNLUNG <- factor(NIS_simple$CM_CHRNLUNG, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_COAG <- factor(NIS_simple$CM_COAG, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_DEPRESS <- factor(NIS_simple$CM_DEPRESS, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_DM <- factor(NIS_simple$CM_DM, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_DMCX <- factor(NIS_simple$CM_DMCX, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_DRUG <- factor(NIS_simple$CM_DRUG, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_HTN_C <- factor(NIS_simple$CM_HTN_C, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_HYPOTHY <- factor(NIS_simple$CM_HYPOTHY, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_LIVER <- factor(NIS_simple$CM_LIVER, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_LYMPH <- factor(NIS_simple$CM_LYMPH, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_LYTES <- factor(NIS_simple$CM_LYTES, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_METS <- factor(NIS_simple$CM_METS, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_NEURO <- factor(NIS_simple$CM_NEURO, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_OBESE <- factor(NIS_simple$CM_OBESE, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_PARA <- factor(NIS_simple$CM_PARA, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_PERIVASC <- factor(NIS_simple$CM_PERIVASC, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_PSYCH <- factor(NIS_simple$CM_PSYCH, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_PULMCIRC <- factor(NIS_simple$CM_PULMCIRC, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_RENLFAIL <- factor(NIS_simple$CM_RENLFAIL, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_TUMOR <- factor(NIS_simple$CM_TUMOR, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_ULCER <- factor(NIS_simple$CM_ULCER, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_VALVE <- factor(NIS_simple$CM_VALVE, levels = c(0,1), labels = c('No', 'Yes'))
NIS_simple$CM_WGHTLOSS <- factor(NIS_simple$CM_WGHTLOSS, levels = c(0,1), labels = c('No', 'Yes'))
```


### Balanced Random Forest (consultation)
```{r}
sm_size <- floor(0.70*nrow(NIS_simple))

set.seed(2019)
train_ind <- sample(seq_len(nrow(NIS_simple)), size = sm_size)

train <- NIS_simple[train_ind, ]
test <- NIS_simple[-train_ind, ]
```

```{r}
#check for balanced in lab code
# NIS_brf <- randomForest(DIED ~ ., data = train,
#                         mtry = sqrt(47),
#                         ntree = 500,
#                         strata = train$DIED,
#                         sampsize = c(3629, 3629))
# NIS_brf
```








